### DISCUSSION TITLE
sticker doesn't work

### DISCUSSION THREAD

**Discussion by skierro** [GioF71/mpd-alsa-docker#378] [Q&A] [answered]
Strange, but till yesterday the sticker db worked without any problem. Today is not. What I should check to be sure that mpd is using sticker? MyMPD doesn't show any statistics / song likes also... :-(

Docker compose file:

```
  mpd:
    image: giof71/mpd-alsa:latest
    container_name: mpd
    ports:
      - "6600:6600"
      - "8800:8000"
      - "8801:8001"
    environment:
      - TZ=Europe/Warsaw
      - STDERR_ENABLED=NO
      - MPD_ENABLE_LOGGING=YES
      #- MPD_LOG_LEVEL=default
      - MPD_LOG_LEVEL=verbose
      - RESTORE_PAUSED=NO
      - DEFAULT_PERMISSIONS=read,add,player
      - LOCAL_PERMISSIONS=read,add,control,admin
      - PASSWORD=REDACTED@read,add,control,admin
      - USER_MODE=yes
      - PUID=1005
      - PGID=1006
      - AUDIO_GID=63

        # hardware output to Onkyo amplifier for the device plughw:0,0)
      - ALSA_OUTPUT_CREATE=yes
      - ALSA_OUTPUT_ENABLED=yes
      - ALSA_OUTPUT_NAME=Onkyo dev 0
      - ALSA_OUTPUT_DEVICE=plughw:0,0
      - ALSA_OUTPUT_MIXER_TYPE=none
      - ALSA_OUTPUT_AUTO_FIND_MIXER=no
      - ALSA_OUTPUT_AUTO_RESAMPLE=no

        # hardware output to Onkyo amplifier for the device plughw:2,0
      - ALSA_OUTPUT_CREATE_1=yes
      - ALSA_OUTPUT_ENABLED_1=yes
      - ALSA_OUTPUT_NAME_1=Onkyo dev 2
      - ALSA_OUTPUT_DEVICE_1=plughw:2,0
      - ALSA_OUTPUT_MIXER_TYPE_1=none
      - ALSA_OUTPUT_AUTO_FIND_MIXER_1=no
      - ALSA_OUTPUT_AUTO_RESAMPLE_1=no
      
        # httpd output (mp3 256 kbps) -> TCP port 8000
      - HTTPD_OUTPUT_CREATE=yes
      - HTTPD_OUTPUT_NAME=mp3 256 kbps
      - HTTPD_OUTPUT_ENABLED=yes
      - HTTPD_OUTPUT_ALWAYS_ON=yes
      - HTTPD_OUTPUT_ENCODER=shine
      - HTTPD_OUTPUT_ENCODER_BITRATE=256

        # httpd output (wave losseless) -> TCP port 8001
      - HTTPD_OUTPUT_CREATE_1=yes
      - HTTPD_OUTPUT_NAME_1=wave
      - HTTPD_OUTPUT_ENABLED_1=yes
      - HTTPD_OUTPUT_ALWAYS_ON_1=yes
      - HTTPD_OUTPUT_ENCODER_1=wave
      - HTTPD_OUTPUT_FORMAT_1=*:*:*
      
    volumes:
      - /docker_data/mpd/db/:/db/:rw
      - /docker_data/mpd/log/:/log/:rw
      - /docker_data/mpd/config/:/user/config/:rw
      - /media/wdc_3tb/shire-media/audio/:/music/:ro
      - /media/wdc_3tb/shire-media/audio/playlists/:/playlists/:ro
    devices:
      - "/dev/snd:/dev/snd"
    restart: unless-stopped
```

**Comment by GioF71** [comment]
Hello, can you post the container logs?
Also, show the permissions of the directory mounted to /db and /log with something like

ls -lad /docker_data/mpd/db
ls -lad /docker_data/mpd/log

Thank you

**Reply by skierro** [reply]
Strange, but the sticker base came back about a few minutes ago.... I don't know what affects it, maybe you can find something in the log?
Here's the permissions:
```
[root@shire-nas ~]# ls -lad /docker_data/mpd/db
drwxr-xr-x. 2 airsonic airsonic 4096 01-25 12:24 /docker_data/mpd/db

[root@shire-nas ~]# ls -lad /docker_data/mpd/log
drwxr-xr-x. 2 airsonic airsonic 4096 01-25 12:22 /docker_data/mpd/log
```
User airsonic is used for the mpd.

---
The container log:
[mpd.log](https://github.com/GioF71/mpd-alsa-docker/files/14051043/mpd.log)

**Reply by GioF71** [reply]
Permissions seem to be ok. The log is quite verbose but still I cannot find any particular issue. 
Maybe you changed the mounted folder to /music, or something similar? If you have to do similar changes, usually rebuilding the db is enough to fix. But this is not done automatically by the container. MyMPD can trigger the db rebuild IIRC

**Reply by skierro** [reply]
I discovered that myMPD was the culprit. It was turning on too fast before the mpd container was ready enough and ignoring the sticker db.

Now it's OK with the 'depends_on' directive in the docker compose file and the healthcheck option with this nifty script: [https://github.com/vishnubob/wait-for-it](https://github.com/vishnubob/wait-for-it)

**Reply by GioF71** [reply]
awesome! Thank you for sharing the solution. Can you also post the docker-compose with the mympd service included?

**Reply by skierro** [reply, marked as answer]
;-)
Here you are:
```
version: "3.8"
services:

  mpd:
    image: giof71/mpd-alsa:latest
    container_name: mpd
    ports:
      - "6600:6600"
      - "8800:8000"
      - "8801:8001"
    environment:
      - TZ=Europe/Warsaw
      - MPD_ENABLE_LOGGING=YES
      # - STDERR_ENABLED=NO  # log to file
      - MPD_LOG_LEVEL=default
      # - MPD_LOG_LEVEL=verbose
      - RESTORE_PAUSED=NO
      - DEFAULT_PERMISSIONS=read,add,player
      - LOCAL_PERMISSIONS=read,add,control,admin
      - PASSWORD=xxxxxxxxxxxxx@read,add,control,player,admin
      - USER_MODE=yes
      - PUID=1005
      - PGID=1006
      - AUDIO_GID=63

        # hardware output to Onkyo amplifier for the device plughw:0,0)
      - ALSA_OUTPUT_CREATE=yes
      - ALSA_OUTPUT_ENABLED=yes
      - ALSA_OUTPUT_NAME=Onkyo dev 0
      - ALSA_OUTPUT_DEVICE=plughw:0,0
      - ALSA_OUTPUT_MIXER_TYPE=none
      - ALSA_OUTPUT_AUTO_FIND_MIXER=no
      - ALSA_OUTPUT_AUTO_RESAMPLE=no

        # hardware output to Onkyo amplifier for the device plughw:2,0
      - ALSA_OUTPUT_CREATE_1=yes
      - ALSA_OUTPUT_ENABLED_1=yes
      - ALSA_OUTPUT_NAME_1=Onkyo dev 2
      - ALSA_OUTPUT_DEVICE_1=plughw:2,0
      - ALSA_OUTPUT_MIXER_TYPE_1=none
      - ALSA_OUTPUT_AUTO_FIND_MIXER_1=no
      - ALSA_OUTPUT_AUTO_RESAMPLE_1=no
      
        # httpd output (mp3 256 kbps) -> TCP port 8000
      - HTTPD_OUTPUT_CREATE=yes
      - HTTPD_OUTPUT_NAME=mp3 256 kbps
      - HTTPD_OUTPUT_ENABLED=yes
      - HTTPD_OUTPUT_ALWAYS_ON=yes
      - HTTPD_OUTPUT_ENCODER=shine
      - HTTPD_OUTPUT_ENCODER_BITRATE=256

        # httpd output (wave losseless) -> TCP port 8001
      - HTTPD_OUTPUT_CREATE_1=yes
      - HTTPD_OUTPUT_NAME_1=wave
      - HTTPD_OUTPUT_ENABLED_1=yes
      - HTTPD_OUTPUT_ALWAYS_ON_1=yes
      - HTTPD_OUTPUT_ENCODER_1=wave
      - HTTPD_OUTPUT_FORMAT_1=*:*:*
      
    volumes:
      - /docker_data/mpd/db/:/db/:rw
      - /docker_data/mpd/log/:/log/:rw
      - /docker_data/mpd/config/:/user/config/:rw
      - /media/wdc_3tb/shire-media/audio/:/music/:ro
      - /media/wdc_3tb/shire-media/audio/playlists/:/playlists/:ro
    devices:
      - "/dev/snd:/dev/snd"
    healthcheck:
      test: /user/config/wait-for-it.sh 192.168.10.31:6600 -q || exit 1
    restart: unless-stopped


  mympd:
    image: ghcr.io/jcorporation/mympd/mympd-devel:devel
    container_name: mympd
    network_mode: "host"
    user: 1005:1006
    depends_on:
      mpd:
        condition: service_healthy
        restart: true
    environment:
      - MYMPD_LOGLEVEL=5
      - UMASK_SET=022
      - TZ=Europe/Warsaw
    volumes:
      - /docker_data/mympd/workdir/:/var/lib/mympd/
      - /docker_data/mympd/cachedir/:/var/cache/mympd/
      - /media/wdc_3tb/shire-media/audio/:/music/:ro
      - /media/wdc_3tb/shire-media/audio/playlists/:/playlists/:rw
    restart: unless-stopped
```
