### ISSUE TITLE
Is it possible to add...

### ISSUE THREAD

**Issue by bonelifer** [GioF71/mpd-alsa-docker#397]
Is it possible to add this to mpd.conf: `auto_update "yes"` Assuming that only causes mpd to pick up new changes and not a total update.

**Comment by GioF71** [comment]
Added support for auto_update_depth while I were at it.
You need to add variable:

AUTO_UPDATE="yes"

for the feature you wanted to have.
Let me know if this works. Images are building right now.

**Comment by bonelifer** [comment]
I'll try this once the docker image updates, didn't work when I did docker pull, so I assume it isnt done propogating/building. Got an error saying "AUTO_UPDATE="yes"" wasn't recognized and mpd never started,

**Comment by GioF71** [comment]
The images have been built in a few minutes so I don't think that is the real issue. Which tag are you using?

**Comment by GioF71** [comment]
Sorry I mislead you, can you try without the quotes? So AUTO_UPDATE=yes

**Comment by GioF71** [comment]
Reopening, until we verify it's ok

**Comment by bonelifer** [comment]
It no longer complains about it.  Doesn't show up in mympd or MPDroid. Don't see it in the log file. Also the log file probably from the mpd.conf, has the characters below. Making gui text editors refuse to open it thinking it's a binary.

`^A^@^@^@^@^@^@`

Had to use this to open this in pluma:
```
#!/bin/bash

# This script removes the pattern ^A^@^@^@^@^@^@ from a file using sed.

# Check if the file path is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

file="$1"

# Use sed to remove the specified pattern from the file
sed -i 's/\x01\x00\x00\x00\x00\x00\x00//g' "$file"
```

**Comment by bonelifer** [comment]
Okay, forgot to add it to the yml file:

`log`
```
Loading preset [topping-e30.device]=[hw:E30]
Finished loading built-in alsa_presets
No additional preset file found
There are [81] available alsa_presets
ANY_PULSE=[1]

ANY_ALSA=[0]
Alsa packages not needed.

USER_MODE=[]
User mode enabled
Creating user ...
Setting default value for PGID: [1000]
Ensuring user with uid:[1000] gid:[1000] exists ...
Group with gid [1000] name [mpd-user] already exists.
user with uid [1000] name [mpd-user] already exists.
drwxr-xr-x 2 mpd-user mpd-user 4096 May  4 16:32 /home/mpd-user
total 8
drwxr-xr-x 2 mpd-user mpd-user 4096 May  4 16:32 .
drwxr-xr-x 1 root     root     4096 May  4 16:32 ..
Creating pulseaudio configuration file /etc/pulse/client.conf...
# Connect to the host's server using the mounted UNIX socket
default-server = unix:/run/user/1000/pulse/native
# Prevent a server running in the container
autospawn = no
daemon-binary = /bin/true
# Prevent the use of shared memory
enable-shm = false
Processing MPD_BIND_ADDRESS index 0
MPD_BIND_ADDRESS at index 0 is set to 0.0.0.0
Processing MPD_BIND_ADDRESS index 1
MPD_BIND_ADDRESS at index 1 is set to 
Processing MPD_BIND_ADDRESS index 2
MPD_BIND_ADDRESS at index 2 is set to 
Processing MPD_BIND_ADDRESS index 3
MPD_BIND_ADDRESS at index 3 is set to 
Processing MPD_BIND_ADDRESS index 4
MPD_BIND_ADDRESS at index 4 is set to 
Processing MPD_BIND_ADDRESS index 5
MPD_BIND_ADDRESS at index 5 is set to 
Processing MPD_BIND_ADDRESS index 6
MPD_BIND_ADDRESS at index 6 is set to 
Processing MPD_BIND_ADDRESS index 7
MPD_BIND_ADDRESS at index 7 is set to 
Processing MPD_BIND_ADDRESS index 8
MPD_BIND_ADDRESS at index 8 is set to 
Processing MPD_BIND_ADDRESS index 9
MPD_BIND_ADDRESS at index 9 is set to 
Processing MPD_BIND_ADDRESS index 10
MPD_BIND_ADDRESS at index 10 is set to 
Processing HOST_PERMISSIONS index 0
HOST_PERMISSIONS at index 0 is set to 
Processing HOST_PERMISSIONS index 1
HOST_PERMISSIONS at index 1 is set to 
Processing HOST_PERMISSIONS index 2
HOST_PERMISSIONS at index 2 is set to 
Processing HOST_PERMISSIONS index 3
HOST_PERMISSIONS at index 3 is set to 
Processing HOST_PERMISSIONS index 4
HOST_PERMISSIONS at index 4 is set to 
Processing HOST_PERMISSIONS index 5
HOST_PERMISSIONS at index 5 is set to 
Processing HOST_PERMISSIONS index 6
HOST_PERMISSIONS at index 6 is set to 
Processing HOST_PERMISSIONS index 7
HOST_PERMISSIONS at index 7 is set to 
Processing HOST_PERMISSIONS index 8
HOST_PERMISSIONS at index 8 is set to 
Processing HOST_PERMISSIONS index 9
HOST_PERMISSIONS at index 9 is set to 
Processing HOST_PERMISSIONS index 10
HOST_PERMISSIONS at index 10 is set to 
Processing PASSWORD index 0
PASSWORD at index 0 is set to 
Processing PASSWORD index 1
PASSWORD at index 1 is set to 
Processing PASSWORD index 2
PASSWORD at index 2 is set to 
Processing PASSWORD index 3
PASSWORD at index 3 is set to 
Processing PASSWORD index 4
PASSWORD at index 4 is set to 
Processing PASSWORD index 5
PASSWORD at index 5 is set to 
Processing PASSWORD index 6
PASSWORD at index 6 is set to 
Processing PASSWORD index 7
PASSWORD at index 7 is set to 
Processing PASSWORD index 8
PASSWORD at index 8 is set to 
Processing PASSWORD index 9
PASSWORD at index 9 is set to 
Processing PASSWORD index 10
PASSWORD at index 10 is set to 
Qobuz Plugin Enabled: []
Creating PULSE_AUDIO output for output [0]
Creating HTTPD output for output [0]
No additional outputs provided
AUTO_UPDATE=[{AUTO_UPDATE}]
Invalid parameter AUTO_UPDATE [{AUTO_UPDATE:-yes}]
```

`.env`
```
HTTPD_OUTPUT_CREATE=yes
HTTPD_OUTPUT_ENABLED=yes
HTTPD_OUTPUT_NAME="HTTP Stream"
HTTPD_OUTPUT_PORT=8000
HTTPD_OUTPUT_BIND_TO_ADDRESS=192.168.1.80
HTTPD_OUTPUT_ENCODER=lame
HTTPD_OUTPUT_ENCODER_BITRATE=320
HTTPD_OUTPUT_MAX_CLIENTS=0
HTTPD_OUTPUT_ALWAYS_ON=yes
HTTPD_OUTPUT_TAGS=yes
HTTPD_OUTPUT_FORMAT=44100:16:2
HTTPD_OUTPUT_MIXER_TYPE=software
PULSE_AUDIO_OUTPUT_CREATE=yes
ENFORCE_PLAYER_STATE=no
AUTO_UPDATE=yes
PUID=1000
GUID=1000
```

`docker-compose.yml:`
```
---
services:
  mpd-alsa:
    container_name: mpd-alsa
    devices:
      - /dev/snd
    ports:
      - 6600:6600
    environment:
      - PULSE_AUDIO_OUTPUT_CREATE=${PULSE_AUDIO_OUTPUT_CREATE:-yes}
#      - MPD_BIND_ADDRESS=${MPD_BIND_ADDRESS:-192.168.1.80}
      - MPD_PORT=${MPD_PORT:-6600}
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
      - HTTPD_OUTPUT_CREATE=${HTTPD_OUTPUT_CREATE:-yes}
      - HTTPD_OUTPUT_ENABLED=${HTTPD_OUTPUT_ENABLED:-yes}
      - HTTPD_OUTPUT_NAME=${HTTPD_OUTPUT_NAME:-HTTP Stream}
      - HTTPD_OUTPUT_PORT=${HTTPD_OUTPUT_PORT:-8000}
      - HTTPD_OUTPUT_BIND_TO_ADDRESS=${HTTPD_OUTPUT_BIND_TO_ADDRESS}
      - HTTPD_OUTPUT_ENCODER=${HTTPD_OUTPUT_ENCODER:-lame}
      - HTTPD_OUTPUT_ENCODER_BITRATE=${HTTPD_OUTPUT_ENCODER_BITRATE}
      - HTTPD_OUTPUT_MAX_CLIENTS=${HTTPD_OUTPUT_MAX_CLIENTS:-0}
      - HTTPD_OUTPUT_ALWAYS_ON=${HTTPD_OUTPUT_ALWAYS_ON:-yes}
      - HTTPD_OUTPUT_TAGS=${HTTPD_OUTPUT_TAGS:-yes}
      - HTTPD_OUTPUT_FORMAT=${HTTPD_OUTPUT_FORMAT:-44100:16:2}
      - HTTPD_OUTPUT_MIXER_TYPE=${HTTPD_OUTPUT_MIXER_TYPE:-software}
      - AUTO_UPDATE={AUTO_UPDATE:-yes}
      - ENFORCE_PLAYER_STATE={ENFORCE_PLAYER_STATE=:-no}

    volumes:
      - /media/william/OracleHarbor/LidarMusic/CLEAN/:/music:ro
      - ./data/.mpd/playlists:/playlists
      - ./data/.mpd/log:/log
      - ./data/.mpd/config:/user/config
      - ./data/.mpd/db:/db
      - /run/user/${PUID}/pulse:/run/user/${PUID}/pulse
    network_mode: "host"  # Add host mode networking
    restart: unless-stopped
    image: giof71/mpd-alsa

```
