### ISSUE TITLE
*.opus exception: Not seekable

### ISSUE THREAD

**Issue by gamebeaker** [GioF71/mpd-alsa-docker#414]
Hello,
thank you for your work.
If i cast my *.opus files i get the exception: `exception: Not seekable`
Is this normal for opus files or are my files the problem?

**Comment by GioF71** [comment]
Hello, I have probably never streamed an opus file. Can you share one with me? I might try anyway by converting one of my files to opus.
Is the file coming from a library or streamed somehow from some upnp server? Can you describe the scenario?

**Comment by GioF71** [comment]
Actually I reproduced your issue by simply adding an opus file which I created using SoundConverter. I am stream from a Lightweight Music Server instance through the subsonic plugin for upmpdcli, and yes, the opus file is not seekable, while the source flac file is perfectly seekable. I'll try to see what is going on and report back...

**Comment by gamebeaker** [comment]
@GioF71 thank you very much.
My setup is that i use [symfonium](https://symfonium.app/) with the option "Proxy via Symfonium" enabled.
I have tried to follow these docker compose file: https://github.com/GioF71/audio-tools/blob/main/players/upnp-renderer/upnp-renderer-simple/docker-compose.yaml
My changed setup files:
<details>
  <summary>docker-compose.yaml</summary>

```
---
version: '3.3'

volumes:
  mpd-db:
  upmpdcli-cache:
  upmpdcli-confdir:

services:
  mpd:
    image: ${MPD_IMAGE_REGISTRY:-docker.io}/giof71/mpd-alsa:${MPD_TAG:-vanilla}
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - MPD_BIND_ADDRESS=${MPD_BIND_ADDRESS:-127.0.0.1}
      - MPD_PORT=${MPD_PORT:-6600}
      - USER_MODE=${MPD_USER_MODE:-N}
      - PUID=${MPD_PUID:-}
      - PGID=${MPD_PGID:-}
      - AUDIO_GID=${MPD_AUDIO_GID:-}
      - ALSA_OUTPUT_CREATE=yes
      - ALSA_OUTPUT_ENABLED=yes
      - ALSA_OUTPUT_DEVICE=${MPD_ALSA_DEVICE:-default}
      - ALSA_OUTPUT_MIXER_TYPE=${MPD_MIXER_TYPE:-software}
      - ALSA_OUTPUT_FORMAT=${MPD_ALSA_OUTPUT_FORMAT:-}
    volumes:
      - mpd-db:/db
    restart: ${RESTART_MODE:-unless-stopped}

  upmpdcli:
    image: ${UPMPDCLI_IMAGE_REGISTRY:-docker.io}/giof71/upmpdcli:${UPMPDCLI_TAG:-latest-renderer}
    network_mode: host
    environment:
      - PUID=${UPMPDCLI_PUID:-}
      - PGID=${UPMPDCLI_PGID:-}
      - MPD_HOST=${MPD_HOST:-127.0.0.1}
      - MPD_PORT=${MPD_PORT:-6600}
      - FRIENDLY_NAME=${FRIENDLY_NAME:-UpnpRenderer}
      - RENDERER_MODE=${RENDERER_MODE:-BOTH}
      - CHECK_CONTENT_FORMAT=${CHECK_CONTENT_FORMAT:-yes}
    volumes:
      - upmpdcli-confdir:/uprcl/confdir
      - upmpdcli-cache:/cache
    restart: ${RESTART_MODE:-unless-stopped}
```

</details>

<details>
  <summary>sample.env</summary>
  
```
COMPOSE_PROJECT_NAME=upnp-renderer-simple

# Restart mode
RESTART_MODE=unless-stopped

# Specify you cache registries for each component
# MPD_IMAGE_REGISTRY=docker.io
# UPMPDCLI_IMAGE_REGISTRY=docker.io

# MPD_TAG=vanilla

# MPD runs app as root by default
# MPD_USER_MODE=N

# Optionally set uid/gid for mpd
# Used if MPD_USER_MODE is set to Y
# Group id for audio is generally 29 on ubuntu/debian distros
# MPD_PUID=1000
# MPD_PGID=1000
# MPD_AUDIO_GID=29

MPD_BIND_ADDRESS=127.0.0.1

MPD_HOST=127.0.0.1

MPD_PORT=6600

# MPD_ALSA_DEVICE examples: 
#   hw:0
#   hw:1
#   hw:DAC
#   hw:D10
MPD_ALSA_DEVICE=default

MPD_MIXER_TYPE=software

# Uncomment for special settings
# MPD_ALSA_OUTPUT_FORMAT=

# Optionally set uid/gid for upmpdcli
# UPMPDCLI_PUID=1000
# UPMPDCLI_PGID=1000

FRIENDLY_NAME=UpnpRenderer5

# RENDERER_MODE values:
#   BOTH
#   UPNPAV
#   OPENHOME
RENDERER_MODE=BOTH
```

</details>
