### ISSUE TITLE
MPD with custom conf

### ISSUE THREAD

**Issue by RomchikL** [GioF71/mpd-alsa-docker#95]
Is it possible to customize mpd.conf with one new output block like

```
audio_output {
	type		"shout"
	encoding	"mp3"			# optional
	name		"Docker MPD Radio"
	host		"icecast"
	port		"8000"
	mount		"/mpd"
	bitrate		"128"
	format		"44100:16:2"
	mixer_type      "software"              # optional
}
```
I try to find a solution for Alsa devices and icecast.
I changed the mpd.conf, restart the container, but all changes disappear.

**Comment by GioF71** [comment]
Hello, yes every change is likely to disappear after each restart, because the configuration file is created when the container starts.
You might be able to force the change by overriding the entrypoint of the container, but in this case the container would not be working as intended.
It might be better and more straightforward to implement a way to use shout as a possible output. I am currently supporting alsa (default), pulse and null, I might add "shout" as well.
Can you describe your scenario? Is this the only output you need to configure for your container?

**Comment by RomchikL** [comment]
Now definitely yes. My scenario is a stack with mpd, ympd, icecast and sima (Autoqueue client). Now mpd should have two outputs (Alsa/Pulse and shout for icecast).
My plans also contain bluetooth speakers support, but I haven't studied this issue in detail. Maybe I'll need a second Alsa/Pulse output.

**Comment by GioF71** [comment]
Would creating two containers, one for alsa and one for icecast, be viable?

**Comment by RomchikL** [comment]
Hmm, I think there will be inconveniences with using (e.g. with ympd). I will also have to duplicate the rest of the services (ympd,sima). And moreover, I will have to play music "simultaneously". I plan to use the Home Assistant integration to control mpd. 
I have [container](https://github.com/VITIMan/docker-music-stack) with "shout" output, but this mpd container does not support alsa. But I can use it only for "shout" output as the second container.

**Comment by GioF71** [comment]
That one is really old!
So what about a stop-gap solution, such as allow a custom file which should contain a snippet of mpd.conf, with custom outputs, which would be added at container startup to the "real" mpd.conf file?

**Comment by RomchikL** [comment]
Old, but fully worked!
Maybe you know a better solution (not mpd, but something else) with support alsa and streaming (only the local net). I tried mopidy, but for this one I should install one more client-side app. 

Your solution  for mpd seems good!

**Comment by GioF71** [comment]
My remark about the repo being old, is only related to the fact that it might be abandoned and is unlikely to be updated anytime soon, I was not saying anything bad at all, of course. All the opposite: the repo has 78 stars, it is probably great and I will have a look at it as soon as I can.

**Comment by RomchikL** [comment]
Excellent!
The snippet is in mpd.conf, the stream via icecast works, local 3.5 speakers also work.

**Comment by GioF71** [comment]
See issue #97

**Comment by GioF71** [comment]
Available in the latest images.
The test image will be deleted soon (meaningless now). So please make sure to revert to the tag you were using (latest, bullseye, jammy maybe).

**Comment by RomchikL** [comment]
Thanks a lot for Your quick reply!
Everything works well. I also configured the pulse audio server and connected my bluetooth speaker. And this config also works fine with the additional output.

**Comment by GioF71** [comment]
Hello @RomchikL, I just added a new feature: we can now add httpd outputs using environment variables. Please check it out when you've got a few minutes.

I would like to do the same also for the shout output using entirely environment variables. Don't worry, the additional output file will be maintained.

What I wanted to ask you is how do you create an instance of shoutcast/icecast server? Are there some docker container images available?
Thank you

**Comment by RomchikL** [comment]
Hello @GioF71!
Super! But I'm not sure that httpd output works properly with my Icecast. But I can try it (maybe a little later).

Yep, I use [that old repo](https://github.com/VITIMan/docker-music-stack), but replaced the original mpd container with yours. My compose if the following:
```
version: '3'

services:
  icecast:
    image: vitiman/alpine-icecast:latest
    container_name: icecast
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - music_stack
      
  mpd:
    image: giof71/mpd-alsa:latest #vitiman/alpine-mpd:latest
    container_name: mpd
    hostname: mpd
    restart: unless-stopped
    ports:
      - "6600:6600"
#      - "8005:8000"
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - /mnt/Data/Media/Music:/music:ro
      - /etc/docker-romchik/configs/mpd/additional-outputs.txt:/user/config/additional-outputs.txt  
      - /mnt/Data/Media/Playlists:/var/lib/mpd/playlists
      - /etc/docker-romchik/configs/mpd/mpd_database:/var/lib/mpd/database
      - /run/user/1000/pulse:/run/user/1000/pulse
    devices:
        - /dev/snd:/dev/snd
    environment:
      - MPD_BIND_ADDRESS=0.0.0.0
      - USER_MODE=Y
      - OUTPUT_MODE=pulse

  ympd:
    image: vitiman/alpine-ympd:latest
    container_name: ympd
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mpd
    networks:
      - music_stack     
      

networks:
  music_stack:
    driver: bridge
```

 In general, I use it for Internet radio with my smart speaker. There is only one way to play a custom audio stream on the speaker - via bluetooth. So, I tell my speaker something like "turn on MPD" -> the speaker communicates with my Home Assistant -> HA play audio on MPD -> one of outputs - pulseaudio, where my speaker is connected via bluetooth =)

But now there is a latency with playing on several speakers (e.g., my smart speaker and my laptop via icecast). But now this issue is not on the agenda

**Comment by GioF71** [comment]
Ok thanks.
I just forked the repo [here](https://github.com/GioF71/docker-music-stack)
And I have updated the alpine and icecast version in the Dockerfile, so if you want to create an updated image, just switch to the `icecast` directory and launch:

```code
docker build . -t vitiman/alpine-icecast:local
```

This really takes a few moments, then you can switch to the `vitiman/alpine-icecast:local` in your compose file.
I have checked the UI and it seems to be working, as far as I understand.
I believe I might create a new repo for icecast, crediting this user of course. I would like to add multiplaform automated builds as with most of my repos. 

I also could add the `shout` output to my container starting from your snippet and I am able to see the mountpoint.
So, sorry for the ignorance, but what is the next step? Which app can I use to verify that this works properly?

If I can test this, I might add the equivalent feature that I added for `httpd` for `shout` as well, hopefully in the next few days.

Thank you for any help!

**Comment by GioF71** [comment]
I got it working with vlc... thanks anyway. In any case, let me know what player(s) you are using downstream.
I will be working on this tomorrow, possibly

**Comment by RomchikL** [comment]
@GioF71 I updated the compose file to use your icecast. Everything seems to be working properly.

Almost any player is suitable (in fact, if there exists the function "open url" in the player). VLC is the most popular, yep.
I also use AIMP. Any browser is also able to open the link, e.g., Chrome.
The URL should be http://IP:8000/mpd (by default with this stack). For me it is http://192.168.1.100:8000/mpd.

**Comment by GioF71** [comment]
Hello @RomchikL, check out the latest release, which allows also multiple shoutcast outputs.
The defaults should almost completely meet your tast and you will need to set just a few variables. For example, I chose `vorbis` as default encoding.
Careful with your snippet: "encoding" is not a valid key, it should be "encoder".
Also, "mp3" is not a valid encoder, you probably want to use "lame" or maybe "vorbis".
After that, you can specify either "quality" or "bitrate". See the documentation for the shout output for more details.

See [here](https://mpd.readthedocs.io/en/stable/plugins.html#shout) for plugin configuration defaults and [here](https://mpd.readthedocs.io/en/stable/plugins.html#encoder-plugins) for the encoders

Let me know if this works for you.
Of course if you configure your shout output via environment variables, you can get rid of the `additional-outputs.txt` file.

**Comment by RomchikL** [comment]
Hello @GioF71. I have configured everything using variables. And this works properly, excellent!
I used this snippet from that repo. see [conf file](https://github.com/VITIMan/docker-music-stack/blob/master/mpd/mpd.conf). And this also works, amazingly! Now I adjusted the encoder, my compose is the following:
```
  mpd:
    image: giof71/mpd-alsa:latest
    container_name: mpd
    hostname: mpd
    restart: unless-stopped
    ports:
      - "6600:6600"
#      - "8005:8000"
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - /mnt/Data/Media/Music:/music:ro
 #     - /etc/docker-romchik/configs/mpd/additional-outputs.txt:/user/config/additional-outputs.txt  
      - /mnt/Data/Media/Playlists:/var/lib/mpd/playlists
      - /etc/docker-romchik/configs/mpd/mpd_database:/var/lib/mpd/database
      - /run/user/1000/pulse:/run/user/1000/pulse
    devices:
        - /dev/snd:/dev/snd
    environment:
      - MPD_BIND_ADDRESS=0.0.0.0
      - USER_MODE=Y
      - OUTPUT_MODE=pulse
      - SHOUT_OUTPUT_CREATE=yes
      - SHOUT_OUTPUT_ENABLED=yes
      - SHOUT_OUTPUT_NAME=MPD Radio
      - SHOUT_OUTPUT_ENCODER_QUALITY=5
      - SHOUT_OUTPUT_MOUNT=/mpd
      - SHOUT_MIXER_TYPE=software
```

**Comment by GioF71** [comment]
Isn't that beautiful?

**Comment by RomchikL** [comment]
Perfect!

**Comment by GioF71** [comment]
BTW I see you use ympd, have you tried mympd? It's miles ahead of ympd.
See [here](https://github.com/jcorporation/myMPD)
It is also quite easily installed with docker

**Comment by RomchikL** [comment]
@GioF71, hello!
I recently updated the container and found the latest changes with "output_mode".
Could you confirm that the new setting is right:
```
  mpd:
    image: giof71/mpd-alsa:latest #giof71/mpd-alsa:legacy-latest
    container_name: mpd
    hostname: mpd
    restart: unless-stopped
    ports:
      - "6600:6600"
    networks:
      - music_stack
    volumes:
      - /mnt/Data/Media/Music:/music:ro
 #     - /etc/docker-romchik/configs/mpd/additional-outputs.txt:/user/config/additional-outputs.txt  
      - /mnt/Data/Media/Playlists:/var/lib/mpd/playlists
      - /etc/docker-romchik/configs/mpd/mpd_database:/var/lib/mpd/database
      - /run/user/1000/pulse:/run/user/1000/pulse
    environment:
#      - OUTPUT_MODE=pulse
      - USER_MODE=Y
      - PULSE_AUDIO_OUTPUT_CREATE=yes
      - PULSE_AUDIO_OUTPUT_ENABLED=yes
      #
      - SHOUT_OUTPUT_CREATE=yes
      - SHOUT_OUTPUT_ENABLED=yes
      - SHOUT_OUTPUT_NAME=MPD Radio
      - SHOUT_OUTPUT_ENCODER_QUALITY=5
      - SHOUT_OUTPUT_MOUNT=/mpd
      - SHOUT_MIXER_TYPE=software
```
This setting does not work with pulse for me ("All outputs are disabled"). MPD Radio works well.

**Comment by GioF71** [comment]
Hello @RomchikL, the configuration looks ok... can you post the container log? That should show the resulting mpd.conf file.
You can read the log by typing

`docker-compose logs mpd`

from the directory where the docker-compose file is.
Also I see there is a restart policy, it usually does not play well with pulseaudio mode. have you tried restarting the container after logging in the desktop environment?

**Comment by GioF71** [comment]
Also, about the "all outputs are disabled" message, can you connect with any mpd client (Cantata for example) and verify it the outputs are actually disabled?

**Comment by GioF71** [comment]
Hello, I just tried this compose file based on yours, and removed anything except pulse, and it works for me:

```
---
version: "3"

services:
  mpd:
    image: giof71/mpd-alsa:latest #giof71/mpd-alsa:legacy-latest
    container_name: mpd
    hostname: mpd
    restart: unless-stopped
    ports:
      - 6600:6600
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ./log:/log
    environment:
      - MPD_LOG_LEVEL=verbose
      - USER_MODE=Y
      - PULSE_AUDIO_OUTPUT_CREATE=yes
      - PULSE_AUDIO_OUTPUT_ENABLED=yes
```

Are you using a user which is actually with uid and gid = 1000? You can verify running

```
id
```
from the command line.
On this laptop I get the following output:

```
➜  test git:(master) ✗ id
uid=1000(giovanni) gid=1000(giovanni) groups=1000(giovanni),3(sys),90(network),98(power),961(docker),991(lp),998(wheel)
```

Also, why are you mounting your directories to those volumes with `/var/lib/mpd/...`? 
The volumes are actually the following:

VOLUME|DESCRIPTION
:---|:---
/db|Where the mpd database is saved
/music|Where the music is stored. You might consider to mount your directory in read-only mode (`:ro`)
/playlists|Where the playlists are stored
/log|Where all logs are written (e.g. `mpd.log`, `scrobbler.log` etc)
/user/config|Additional user-provided configuration files, see [this](#user-configuration-volume) paragraph for the details
